apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.service.name }}
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Values.appname }}
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
